
variable "aws_access_key" {
  type    = string
  default = "AKIA6QANFEY2OYZEVJ4D"
}

variable "aws_secret_key" {
  type    = string
  default = "mJJbz7JxC2d1UM3tsT2iKDEK5Tlgapi+SKm9HyCQ"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

# template: hcl2_upgrade:4:48: executing "hcl2_upgrade" at <clean_resource_name>: error calling clean_resource_name: unhandled "clean_resource_name" call:
# there is no way to automatically upgrade the "clean_resource_name" call.
# Please manually upgrade to use custom validation rules, `replace(string, substring, replacement)` or `regex_replace(string, substring, replacement)`
# Visit https://packer.io/docs/templates/hcl_templates/variables#custom-validation-rules , https://www.packer.io/docs/templates/hcl_templates/functions/string/replace or https://www.packer.io/docs/templates/hcl_templates/functions/string/regex_replace for more infos.

source "amazon-ebs" "autogenerated_1" {
  ami_description = "This is lamp stack"
  ami_name        = "lampfrompacker-{{isotime | clean_resource_name}}"
  communicator    = "ssh"
  instance_type   = "t2.micro"
  region          = "us-west-2"
  source_ami      = "ami-090717c950a5c34d3"
  ssh_username    = "ubuntu"
}

build {
  description = "Create a lamp stack"

  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    script = "lamp.sh"
  }

}
